import { IMAGES } from '@/constants';

export interface ProductData {
  slug: string;
  name: string;
  category: string;
  categoryHref: string;
  heroSubheading: string;
  description: string;
  image: string;
  overviewParagraphs: string[];
  overviewHighlights: string[];
  specs: { label: string; value: string }[];
  applications: { title: string; description: string }[];
  packagingItems: string[];
  qualityItems: string[];
  exportItems: string[];
  metaTitle: string;
  metaDescription: string;
  ogTitle: string;
  ogDescription: string;
}

const products: ProductData[] = [
  // ─── ALUMINUM ───────────────────────────────────────────
  {
    slug: 'aluminum-ingots',
    name: 'Aluminum Ingots',
    category: 'Aluminum Products',
    categoryHref: '/products/aluminum-ingots',
    heroSubheading: 'High-purity aluminum ingots for casting, alloying, extrusion, and industrial manufacturing applications.',
    description: 'Our aluminum ingots are produced under controlled conditions to ensure consistent chemical composition, minimal porosity, and clean surface finish. Suitable for die-casting, sand-casting, and extrusion processes across automotive, construction, and industrial sectors.',
    image: IMAGES.aluminumIngots,
    overviewParagraphs: [
      'RMRP Global Trade supplies high-purity aluminum ingots to industrial buyers and manufacturers across 25+ countries. Our ingots are produced under strict quality controls ensuring consistent composition and clean surface finish.',
      'Available in primary (99.9%) and secondary (99.5%) grades, our ingots serve die-casting, sand-casting, extrusion, and alloying applications across automotive, construction, and industrial manufacturing sectors.',
    ],
    overviewHighlights: ['Consistent purity guaranteed per batch', 'Low gas content and reduced oxide inclusion', 'Custom alloy compositions available', 'Full documentation with every shipment'],
    specs: [
      { label: 'Purity', value: '99.5% – 99.9% Al' },
      { label: 'Weight', value: '6 kg – 25 kg per ingot' },
      { label: 'Shape', value: 'T-bar, sow, or notched ingot' },
      { label: 'Packaging', value: 'Bundled, strapped, or loose' },
      { label: 'Standards', value: 'ASTM B179 / ISO 115' },
    ],
    applications: [
      { title: 'Automotive Manufacturing', description: 'Engine components, body panels, wheels, heat exchangers, and structural parts for passenger and commercial vehicles.' },
      { title: 'Construction & Infrastructure', description: 'Window frames, curtain walls, roofing sheets, scaffolding, and structural profiles for buildings and bridges.' },
      { title: 'Industrial Machinery', description: 'Machine frames, conveyor systems, hydraulic components, and equipment housings requiring lightweight strength.' },
      { title: 'Electrical & Electronics', description: 'Bus bars, transformer windings, heat sinks, cable sheathing, and conductor alloys for power transmission.' },
    ],
    qualityItems: [
      'Chemical composition verified via spectrometric analysis per batch',
      'Dimensional inspection and weight verification before loading',
      'Surface quality check for oxidation, contamination, and defects',
      'Certificate of Analysis (COA) issued with every shipment',
      'Third-party inspection available upon buyer request',
    ],
    packagingItems: [
      'Ingots bundled with steel strapping on pallets for safe handling',
      'Waterproof and moisture-protected for sea freight',
      'Container load: ~20 MT per 20-ft container',
      'Full docs: Bill of Lading, Packing List, Invoice, COA, COO',
    ],
    exportItems: [
      'Container-load quantities (20 MT per 20-ft container)',
      'Bulk vessel shipments for large-volume buyers',
      'Flexible incoterms: FOB, CIF, CFR, EXW',
      'Payment terms: LC, TT, DP negotiable',
      'Dedicated export documentation team',
    ],
    metaTitle: 'Aluminum Ingots',
    metaDescription: 'High-purity aluminum ingots (99.5%–99.9%) for casting, alloying, and extrusion. ASTM/ISO standards. Export quality with full documentation. Inquire for bulk pricing.',
    ogTitle: 'Aluminum Ingots | RMRP Global Trade',
    ogDescription: 'Premium aluminum ingots for industrial manufacturing — consistent purity, custom alloys, export-ready packaging.',
  },
  {
    slug: 'aluminum-scrap',
    name: 'Aluminum Scrap',
    category: 'Aluminum Products',
    categoryHref: '/products/aluminum-ingots',
    heroSubheading: 'All grades of sorted aluminum scrap for recycling facilities, secondary smelters, and foundries worldwide.',
    description: 'We supply a comprehensive range of sorted and graded aluminum scrap meeting ISRI specifications. Our scrap is processed, cleaned, and inspected for consistent metal content and purity.',
    image: IMAGES.aluminumScrap,
    overviewParagraphs: [
      'RMRP Global Trade supplies sorted and graded aluminum scrap to recycling facilities, secondary smelters, and foundries across 25+ countries. All scrap is processed and inspected to meet international grading standards.',
      'From Zorba and Twitch to UBC and turnings, we offer a full range of aluminum scrap grades with guaranteed metal content, composition analysis, and moisture verification.',
    ],
    overviewHighlights: ['Sorted per ISRI specifications', 'Metal content guaranteed with analysis', 'Shredded, sheared, or baled options', 'Moisture content verified for net weight'],
    specs: [
      { label: 'Grades', value: 'Zorba, Twitch, 6061/6063, Litho, UBC, Turnings, MLC' },
      { label: 'Form', value: 'Shredded, sheared, baled, or loose' },
      { label: 'Loading', value: 'Container or bulk vessel' },
      { label: 'Inspection', value: 'Composition analysis per load' },
      { label: 'Standards', value: 'ISRI specifications' },
    ],
    applications: [
      { title: 'Secondary Smelting', description: 'Sorted scrap grades for secondary aluminum producers manufacturing foundry alloys and deoxidizing agents.' },
      { title: 'Automotive Recycling', description: 'Zorba and Twitch grades for automotive shredder residue processing and metal recovery.' },
      { title: 'Building & Construction', description: 'Extrusion scrap (6061/6063) remelted for new architectural profiles and structural sections.' },
      { title: 'Packaging Recycling', description: 'UBC scrap for closed-loop can sheet production in the beverage packaging industry.' },
    ],
    qualityItems: [
      'Sorted and graded per ISRI specifications',
      'Metal content guaranteed with composition analysis report',
      'Moisture content verified for accurate net weight billing',
      'Dedicated inspection before loading for every shipment',
      'Third-party weight and quality verification available',
    ],
    packagingItems: [
      'Container compaction loading for optimal weight utilization',
      'Open-top containers for heavy scrap grades',
      'Bulk vessel loading for large volumes',
      'Weight Certificate, Composition Analysis, Packing List, COO',
    ],
    exportItems: [
      'Container-load: 20–25 MT per container depending on grade',
      'Open-top container and bulk vessel options',
      'Fumigation certificate provided for wooden packaging',
      'Flexible payment terms: LC, TT, and other structures',
      'Full documentation for customs clearance',
    ],
    metaTitle: 'Aluminum Scrap',
    metaDescription: 'All grades of aluminum scrap — Zorba, Twitch, 6061/6063, Litho, UBC, turnings, and more. Sorted per ISRI specs. Export quality. Inquire for pricing.',
    ogTitle: 'Aluminum Scrap | RMRP Global Trade',
    ogDescription: 'Comprehensive range of sorted aluminum scrap grades for global recycling and secondary smelting industries.',
  },
  // ─── PROCESSED FOOD ─────────────────────────────────────
  {
    slug: 'jaggery',
    name: 'Jaggery & Jaggery Powder',
    category: 'Processed Food',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Natural unrefined cane sugar in block and powder form. Premium quality, hygienically processed, and export-grade packaged.',
    description: 'Traditional jaggery made from pure sugarcane juice, available in solid blocks and free-flowing powder. Rich in minerals with natural sweetness for food manufacturing and direct consumption.',
    image: IMAGES.jaggery,
    overviewParagraphs: [
      'Our jaggery is produced from fresh sugarcane juice using traditional boiling and filtration methods, preserving natural minerals and molasses content. Available in solid block and powdered forms.',
      'Jaggery powder offers consistent granulation for easy handling and dissolution in industrial food processing, bakery applications, and direct consumer packaging.',
    ],
    overviewHighlights: ['Natural & unrefined with rich mineral content', 'Available in block and free-flowing powder', 'Hygienically processed in food-grade facilities', 'Export-grade packaging with extended shelf life'],
    specs: [
      { label: 'Form', value: 'Solid block / Free-flowing powder' },
      { label: 'Color', value: 'Golden brown to dark brown' },
      { label: 'Packaging', value: '5 kg, 10 kg, 25 kg cartons' },
      { label: 'Shelf Life', value: '24 months' },
      { label: 'Origin', value: 'India' },
    ],
    applications: [
      { title: 'Food Processing', description: 'Natural sweetener for confectionery, bakery, sauces, and traditional sweet manufacturing.' },
      { title: 'Beverage Industry', description: 'Base ingredient for traditional drinks, health beverages, and alcoholic fermentation.' },
      { title: 'Nutraceuticals', description: 'Mineral-rich natural sweetener for health foods, supplements, and Ayurvedic formulations.' },
      { title: 'Retail & Consumer', description: 'Direct consumer packaging for household cooking and natural sweetening needs.' },
    ],
    qualityItems: [
      'Produced in food-grade facilities with HACCP protocols',
      'Tested for heavy metals, pesticides, and microbiological contaminants',
      'Moisture content controlled for optimal shelf life',
      'Metal detection at packaging stage',
      'Certificate of Analysis issued with every shipment',
    ],
    packagingItems: [
      'Food-grade cartons with inner polyethylene liner',
      'Moisture-proof sealed packaging for humidity protection',
      'Available in 5 kg, 10 kg, and 25 kg pack sizes',
      'Pallets shrink-wrapped for container loading',
    ],
    exportItems: [
      'Container-load: 20–24 MT per 20-ft container',
      'LCL options available for trial orders',
      'Flexible incoterms: FOB, CIF, CFR, EXW',
      'Full documents: Packing List, Invoice, COO, Health Certificate',
      'Fumigation certificate provided as required',
    ],
    metaTitle: 'Jaggery & Jaggery Powder',
    metaDescription: 'Natural unrefined jaggery in block and powder form. Premium quality, hygienically processed, export-grade packaged. Bulk supply from India. Inquire now.',
    ogTitle: 'Jaggery & Jaggery Powder | RMRP Global Trade',
    ogDescription: 'Premium quality jaggery and jaggery powder for global buyers — natural, mineral-rich, and export-ready.',
  },
  {
    slug: 'onion-powder',
    name: 'Onion Powder',
    category: 'Processed Food',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Dehydrated onion powder with strong flavor retention and uniform particle size for seasoning, soup, sauce, and ready-meal manufacturing.',
    description: 'Premium dehydrated onion powder with consistent fine granulation, strong aroma, and quick dissolution. Ideal for dry seasonings, spice blends, and industrial food processing.',
    image: IMAGES.onionPowder,
    overviewParagraphs: [
      'Our onion powder is manufactured from fresh onions using controlled drying and milling processes that preserve natural flavor, color, and nutritional properties.',
      'With uniform particle size and strong flavor retention, our onion powder serves seasoning manufacturers, soup producers, snack food companies, and industrial food processors worldwide.',
    ],
    overviewHighlights: ['Strong flavor and aroma retention', 'Uniform fine powder (80–100 mesh)', 'Moisture content < 6%', 'No artificial additives or preservatives'],
    specs: [
      { label: 'Form', value: 'Fine free-flowing powder' },
      { label: 'Color', value: 'White to pale cream' },
      { label: 'Moisture', value: '< 6%' },
      { label: 'Packaging', value: '10 kg, 20 kg, 25 kg bags' },
      { label: 'Shelf Life', value: '18 months' },
    ],
    applications: [
      { title: 'Seasoning & Spice Blends', description: 'Base ingredient for dry rubs, marinades, seasoning mixes, and spice blends for retail and industrial use.' },
      { title: 'Soup & Sauce Manufacturing', description: 'Dehydrated onion for instant soups, stock cubes, sauces, gravies, and bouillon production.' },
      { title: 'Snack Foods', description: 'Flavored snack seasonings, extruded snack coatings, and savory seasoning applications.' },
      { title: 'Food Service', description: 'Bulk onion powder for hotels, restaurants, catering, and institutional kitchens.' },
    ],
    qualityItems: [
      'Raw material inspection at farm level',
      'In-process checks during dehydration and milling',
      'Finished product analysis: moisture, particle size, microbiological',
      'Metal detection and foreign matter removal',
      'Third-party lab testing available on request',
    ],
    packagingItems: [
      'Multi-layer paper bags with inner PE liner',
      'Moisture-protected for sea freight',
      'Custom pack sizes available',
      'Private labeling for retail and distribution',
    ],
    exportItems: [
      'Container-load: 14–18 MT per 20-ft container',
      'LCL options for trial quantities',
      'Full documentation: Packing List, Invoice, COO, Health Certificate',
      'Phytosanitary certificate provided as required',
      'Flexible payment terms negotiable',
    ],
    metaTitle: 'Onion Powder',
    metaDescription: 'Premium dehydrated onion powder, strong flavor retention, uniform fine mesh. Ideal for seasonings, soups, sauces, and snack foods. Bulk export quality from India.',
    ogTitle: 'Onion Powder | RMRP Global Trade',
    ogDescription: 'Premium dehydrated onion powder for global food manufacturers — consistent quality, export-ready packaging.',
  },
  {
    slug: 'onion-flakes',
    name: 'Onion Flakes',
    category: 'Processed Food',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Dehydrated onion flakes in kibbled, minced, and flaked forms for quick rehydration in soups, stews, curries, and ready meals.',
    description: 'Premium dehydrated onion flakes with consistent cut size, quick rehydration, and retained natural flavor. Available in kibbled, minced, and flaked granulations.',
    image: IMAGES.onionFlakes,
    overviewParagraphs: [
      'Our onion flakes are produced from fresh onions using controlled dehydration that preserves natural flavor, texture, and color while ensuring quick rehydration.',
      'Available in multiple granulations from coarse kibbled to fine minced, our onion flakes serve soup manufacturers, ready-meal producers, and food service operators worldwide.',
    ],
    overviewHighlights: ['Multiple granulations: kibbled, minced, flaked', 'Quick rehydration in warm water', 'Natural color and flavor retention', 'No artificial additives or preservatives'],
    specs: [
      { label: 'Form', value: 'Kibbled / Minced / Flakes' },
      { label: 'Color', value: 'White to pale cream' },
      { label: 'Moisture', value: '< 6%' },
      { label: 'Packaging', value: '10 kg, 20 kg, 25 kg bags' },
      { label: 'Shelf Life', value: '18 months' },
    ],
    applications: [
      { title: 'Soup & Stew Manufacturing', description: 'Quick-rehydrating flakes for instant soups, stews, broths, and bouillon with visible onion pieces.' },
      { title: 'Ready Meals & Curries', description: 'Textured onion pieces for frozen meals, curry kits, and prepared food products requiring visible ingredients.' },
      { title: 'Food Service & HoReCa', description: 'Bulk onion flakes for hotels, restaurants, catering operations, and institutional food preparation.' },
      { title: 'Meat & Savory Processing', description: 'Flavored ingredient for sausages, meat pies, savory pastries, and processed meat products.' },
    ],
    qualityItems: [
      'Raw material inspection at farm level',
      'In-process checks during dehydration and cutting',
      'Finished product analysis: moisture, particle size, microbiological',
      'Metal detection and foreign matter removal',
      'Third-party lab testing available on request',
    ],
    packagingItems: [
      'Multi-layer paper bags with inner PE liner',
      'Moisture-protected for sea freight',
      'Custom cut sizes and pack sizes available',
      'Private labeling for retail and distribution',
    ],
    exportItems: [
      'Container-load: 14–18 MT per 20-ft container',
      'LCL options for trial quantities',
      'Full documentation: Packing List, Invoice, COO, Health Certificate',
      'Phytosanitary certificate provided as required',
      'Flexible payment terms negotiable',
    ],
    metaTitle: 'Onion Flakes',
    metaDescription: 'Premium dehydrated onion flakes — kibbled, minced, and flaked forms. Quick rehydration, natural flavor. Bulk export from India for soup, ready-meal, and food service industries.',
    ogTitle: 'Onion Flakes | RMRP Global Trade',
    ogDescription: 'High-quality dehydrated onion flakes for global food manufacturers and food service — consistent cut, quick rehydration.',
  },
  {
    slug: 'garlic-powder',
    name: 'Garlic Powder',
    category: 'Processed Food',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Pure dehydrated garlic powder with high allicin retention and fine mesh for seasoning, spice blends, and industrial food processing.',
    description: 'Premium dehydrated garlic powder with high allicin retention, fine uniform mesh, and pure composition. No fillers or additives for clean-label food manufacturing.',
    image: IMAGES.garlicPowder,
    overviewParagraphs: [
      'Our garlic powder is processed from fresh Indian garlic using low-temperature drying that preserves allicin content and natural flavor compounds.',
      'With fine mesh (80–100) for uniform dispersion, our garlic powder serves seasoning manufacturers, spice blenders, meat processors, and industrial food manufacturers worldwide.',
    ],
    overviewHighlights: ['High allicin retention from low-temp drying', 'Fine mesh 80–100 for uniform dispersion', 'Pure product with no fillers or additives', 'Microbiologically tested for food safety'],
    specs: [
      { label: 'Form', value: 'Fine powder' },
      { label: 'Color', value: 'Pale cream to light yellow' },
      { label: 'Mesh Size', value: '80–100' },
      { label: 'Packaging', value: '10 kg, 20 kg, 25 kg bags' },
      { label: 'Shelf Life', value: '18 months' },
    ],
    applications: [
      { title: 'Seasoning & Spice Blends', description: 'Essential ingredient for garlic salt, seasoning blends, marinades, and dry rub formulations.' },
      { title: 'Meat & Poultry Processing', description: 'Dry seasoning for sausages, processed meats, marinated products, and ready-to-cook preparations.' },
      { title: 'Soup, Sauce & Snack Foods', description: 'Garlic flavor for instant soups, pasta sauces, snack seasonings, and savory food products.' },
      { title: 'Food Service & Institutional', description: 'Bulk garlic powder for hotels, restaurants, catering operations, and central kitchens.' },
    ],
    qualityItems: [
      'Low-temperature drying preserves allicin content',
      'Finished product analysis for moisture, purity, microbiology',
      'Metal detection and sieve analysis at packaging',
      'Microbiological testing: TPC, Yeast & Mold, Coliforms, Salmonella, E. coli',
      'Certificate of Analysis issued per batch',
    ],
    packagingItems: [
      'Multi-layer paper bags with inner PE liner for moisture barrier',
      'Vacuum-sealed options for bulk packs',
      'Custom pack sizes from 5 kg to 25 kg',
      'Private labeling and retail packaging available',
    ],
    exportItems: [
      'Container-load: 14–18 MT per 20-ft container',
      'LCL for trial and smaller orders',
      'Full documentation: Packing List, Invoice, COO, Health Certificate',
      'Phytosanitary and fumigation certificates as required',
      'Flexible incoterms and payment terms',
    ],
    metaTitle: 'Garlic Powder',
    metaDescription: 'Premium dehydrated garlic powder, high allicin retention, fine mesh 80–100, pure no fillers. Bulk export from India for seasoning, meat processing, and food manufacturing.',
    ogTitle: 'Garlic Powder | RMRP Global Trade',
    ogDescription: 'Premium quality dehydrated garlic powder for global food manufacturers — pure, potent, and export-ready.',
  },
  {
    slug: 'garlic-flakes',
    name: 'Garlic Flakes',
    category: 'Processed Food',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Dehydrated garlic flakes and granules with quick rehydration and retained flavor intensity for processed meats, sauces, and ready meals.',
    description: 'Premium dehydrated garlic flakes with uniform cut size, quick rehydration, and intense natural flavor. Ideal for visible garlic pieces in processed foods.',
    image: IMAGES.garlicFlakes,
    overviewParagraphs: [
      'Our garlic flakes are processed from fresh Indian garlic using low-temperature dehydration that preserves natural flavor, color, and appearance.',
      'Available in flaked and granulated forms, our garlic products serve meat processors, soup manufacturers, ready-meal producers, and food service operators worldwide.',
    ],
    overviewHighlights: ['Quick rehydration with flavor intensity', 'Uniform cut size for consistent appearance', 'Low microbial count for food safety', 'Pure product with no additives'],
    specs: [
      { label: 'Form', value: 'Flakes / Granules' },
      { label: 'Color', value: 'Pale cream to light yellow' },
      { label: 'Moisture', value: '< 6%' },
      { label: 'Packaging', value: '10 kg, 20 kg, 25 kg bags' },
      { label: 'Shelf Life', value: '18 months' },
    ],
    applications: [
      { title: 'Meat & Savory Processing', description: 'Visible garlic pieces for sausages, processed meats, meat pies, and savory pastry products.' },
      { title: 'Soup & Ready Meal Manufacturing', description: 'Quick-rehydrating flakes for instant soups, broths, ready meals, and meal kit components.' },
      { title: 'Sauce & Marinade Production', description: 'Textured garlic for pasta sauces, curry pastes, marinades, and liquid seasoning preparations.' },
      { title: 'Food Service & HoReCa', description: 'Bulk garlic flakes for hotels, restaurants, catering, and institutional food service.' },
    ],
    qualityItems: [
      'Low-temperature drying preserves natural flavor',
      'Finished product analysis for moisture, purity, microbiology',
      'Metal detection and sieve analysis at packaging',
      'Microbiological testing per food safety standards',
      'Certificate of Analysis issued per batch',
    ],
    packagingItems: [
      'Multi-layer paper bags with inner PE liner',
      'Moisture-protected for sea freight',
      'Custom cut sizes and pack sizes available',
      'Private labeling for distribution brands',
    ],
    exportItems: [
      'Container-load: 14–18 MT per 20-ft container',
      'LCL for trial and smaller orders',
      'Full documentation: Packing List, Invoice, COO, Health Certificate',
      'Phytosanitary and fumigation certificates as required',
      'Flexible incoterms and payment terms',
    ],
    metaTitle: 'Garlic Flakes',
    metaDescription: 'Premium dehydrated garlic flakes and granules with quick rehydration and intense flavor. Ideal for meat processing, soups, sauces, and ready meals. Bulk export from India.',
    ogTitle: 'Garlic Flakes | RMRP Global Trade',
    ogDescription: 'High-quality dehydrated garlic flakes for global food manufacturers — consistent cut, quick rehydration, export-ready.',
  },
  {
    slug: 'banana-powder',
    name: 'Banana Powder',
    category: 'Processed Food',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Spray-dried green banana powder rich in resistant starch and dietary fiber for nutraceutical and health food applications.',
    description: 'Spray-dried green banana powder with high resistant starch content. Natural prebiotic ingredient for nutritional supplements, baby food, and gluten-free formulations.',
    image: IMAGES.bananaPowder,
    overviewParagraphs: [
      'Our banana powder is produced from raw green bananas using spray-drying technology that preserves natural resistant starch, dietary fiber, and nutritional properties.',
      'A clean-label ingredient rich in prebiotic fiber, our banana powder serves the nutraceutical, baby food, sports nutrition, and gluten-free food industries.',
    ],
    overviewHighlights: ['Spray-dried for consistent quality', 'High resistant starch content', 'Gluten-free and clean label', 'Extended 24-month shelf life'],
    specs: [
      { label: 'Form', value: 'Fine free-flowing powder' },
      { label: 'Color', value: 'Off-white to light cream' },
      { label: 'Resistant Starch', value: '> 50%' },
      { label: 'Packaging', value: '10 kg, 20 kg, 25 kg bags with inner liner' },
      { label: 'Shelf Life', value: '24 months' },
    ],
    applications: [
      { title: 'Nutritional Supplements', description: 'Natural prebiotic fiber source for protein powders, meal replacements, and dietary supplement formulations.' },
      { title: 'Baby Food', description: 'Gentle, easily digestible carbohydrate source for infant cereals, purees, and baby snack products.' },
      { title: 'Gluten-Free Baking', description: 'Flour alternative and texture enhancer for gluten-free breads, cookies, cakes, and bakery mixes.' },
      { title: 'Sports Nutrition', description: 'Natural energy source with slow-digesting carbohydrates for sports bars, gels, and recovery products.' },
    ],
    qualityItems: [
      'Spray-dried under controlled temperature conditions',
      'Microbiological testing for pathogens and contaminants',
      'Moisture content analysis for optimal powder stability',
      'Resistant starch content verified per batch',
      'Food-grade production facility with HACCP protocols',
    ],
    packagingItems: [
      'Multi-layer bags with inner aluminum foil liner for moisture/oxygen barrier',
      'Vacuum-sealed bulk packs available',
      'Nitrogen flushing for extended shelf life',
      'Custom retail and industrial pack sizes',
    ],
    exportItems: [
      'Container-load: 12–16 MT per 20-ft container',
      'LCL for trial orders available',
      'Full export documentation provided',
      'Cool container options for sensitive shipments',
      'Flexible incoterms and payment structures',
    ],
    metaTitle: 'Banana Powder',
    metaDescription: 'Spray-dried green banana powder with high resistant starch. Natural prebiotic for nutraceuticals, baby food, and gluten-free products. Bulk export quality from India.',
    ogTitle: 'Banana Powder | RMRP Global Trade',
    ogDescription: 'Premium spray-dried banana powder rich in resistant starch — clean label ingredient for health food and supplement industries.',
  },
  {
    slug: 'tomato-flakes',
    name: 'Tomato Flakes',
    category: 'Processed Food',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Dehydrated tomato flakes with vibrant red color and concentrated flavor for soups, sauces, pizza, and instant meals.',
    description: 'Premium dehydrated tomato flakes manufactured from ripe red tomatoes. Quick rehydration with retained color, flavor, and nutritional value for industrial food processing.',
    image: IMAGES.tomatoFlakes,
    overviewParagraphs: [
      'Our tomato flakes are produced from vine-ripened red tomatoes using controlled dehydration that preserves natural color, lycopene content, and concentrated tomato flavor.',
      'Quick rehydration makes them ideal for soup mixes, sauce bases, pizza toppings, instant meals, and food service applications requiring consistent tomato flavor.',
    ],
    overviewHighlights: ['Vibrant red color retention', 'Concentrated natural tomato flavor', 'Quick rehydration in warm water', 'No preservatives or artificial colors'],
    specs: [
      { label: 'Form', value: 'Dehydrated flakes' },
      { label: 'Color', value: 'Bright red' },
      { label: 'Moisture', value: '< 8%' },
      { label: 'Packaging', value: '10 kg, 15 kg, 20 kg bags' },
      { label: 'Shelf Life', value: '18 months' },
    ],
    applications: [
      { title: 'Soup & Sauce Manufacturing', description: 'Concentrated tomato flavor for instant soups, pasta sauces, ketchup, and tomato-based culinary products.' },
      { title: 'Pizza & Ready Meals', description: 'Quick rehydrating topping for pizza manufacturing, ready meals, and frozen food products.' },
      { title: 'Snack Foods', description: 'Tomato flavor component for snack seasonings, extruded snacks, and savory coated products.' },
      { title: 'Food Service', description: 'Bulk dehydrated tomato for hotels, restaurants, catering, and institutional food preparation.' },
    ],
    qualityItems: [
      'Tomato sourcing from trusted growing regions',
      'Color and flavor analysis per production batch',
      'Moisture content verification for shelf stability',
      'Metal detection and screening at packaging',
      'Microbiological testing per food safety standards',
    ],
    packagingItems: [
      'Multi-layer paper bags with inner PE liner',
      'Moisture-protected packaging for sea freight',
      'Custom pack sizes for industrial and food service',
      'Private labeling available for distribution brands',
    ],
    exportItems: [
      'Container-load: 12–16 MT per 20-ft container',
      'LCL options for smaller orders',
      'Full documentation: Packing List, Invoice, COO, Health Certificate',
      'Phytosanitary certificate as required',
      'Competitive freight rates through established partnerships',
    ],
    metaTitle: 'Tomato Flakes',
    metaDescription: 'Premium dehydrated tomato flakes with vibrant color and concentrated flavor. Quick rehydration, no preservatives. Bulk export from India. Inquire for pricing.',
    ogTitle: 'Tomato Flakes | RMRP Global Trade',
    ogDescription: 'High-quality dehydrated tomato flakes for global food manufacturers — natural flavor, export-ready packaging.',
  },
  // ─── AGRO PRODUCTS ──────────────────────────────────────
  {
    slug: 'sugar',
    name: 'Sugar (ICUMSA 45)',
    category: 'Agro Products',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Premium refined white sugar meeting ICUMSA 45 standards for FMCG, confectionery, beverage, and pharmaceutical industries.',
    description: 'Premium refined white sugar with bright white crystals and consistent granulation. Meets ICUMSA 45 international standards for food and beverage manufacturing.',
    image: IMAGES.sugar,
    overviewParagraphs: [
      'Our refined white sugar is manufactured from high-quality sugarcane using modern refining processes that produce bright white crystals with consistent granulation and purity.',
      'Meeting ICUMSA 45 standards, our sugar serves FMCG manufacturers, confectionery producers, beverage companies, and pharmaceutical applications requiring premium grade sweetener.',
    ],
    overviewHighlights: ['ICUMSA 45 certified premium grade', 'Bright white crystals, consistent granulation', 'Free-flowing with anti-caking treatment', 'Bulk vessel and container loading capable'],
    specs: [
      { label: 'Grade', value: 'ICUMSA 45' },
      { label: 'Color', value: 'Bright white' },
      { label: 'Granulation', value: 'Fine to medium' },
      { label: 'Packaging', value: '50 kg PP bags, 1 MT jumbo bags, bulk liners' },
      { label: 'Shelf Life', value: '36 months' },
    ],
    applications: [
      { title: 'FMCG & Beverage', description: 'Sweetener for soft drinks, juices, energy drinks, and packaged food products requiring consistent quality.' },
      { title: 'Confectionery & Bakery', description: 'Essential ingredient for candies, chocolates, biscuits, cakes, and all confectionery manufacturing.' },
      { title: 'Pharmaceutical', description: 'High-purity sugar for syrup bases, excipients, and pharmaceutical formulations requiring premium grade.' },
      { title: 'Food Processing', description: 'Industrial sweetener for sauces, preserves, canned fruits, and processed food manufacturing.' },
    ],
    qualityItems: [
      'ICUMSA 45 certified with lab analysis per batch',
      'Color, polarity, moisture, and ash content verified',
      'Free from contaminants and foreign matter',
      'Food-grade production with quality management systems',
      'Certificate of Analysis issued with every shipment',
    ],
    packagingItems: [
      '50 kg PP bags with inner liner for moisture protection',
      '1 MT jumbo bags for bulk handling efficiency',
      'Bulk container liner systems for large-volume shipments',
      'Custom packaging and private labeling available',
    ],
    exportItems: [
      'Container-load: 26 MT per 20-ft container',
      'Bulk vessel shipment capability for large volumes',
      'Full documentation: Packing List, Invoice, COO, Health Certificate',
      'Certificate of Origin for preferential trade agreements',
      'Flexible incoterms: FOB, CIF, CFR, EXW',
    ],
    metaTitle: 'Sugar (ICUMSA 45)',
    metaDescription: 'Premium refined white sugar ICUMSA 45. Bright white crystals, consistent granulation. Bulk and container export. Serving FMCG, beverage, confectionery, pharmaceutical industries.',
    ogTitle: 'Sugar ICUMSA 45 | RMRP Global Trade',
    ogDescription: 'Premium refined sugar meeting ICUMSA 45 standards for global industrial buyers — consistent quality, competitive pricing.',
  },
  {
    slug: 'millet-flour',
    name: 'Millet (Bajra) Flour',
    category: 'Agro Products',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Stone-ground pearl millet flour with high fiber, protein, and mineral content. Gluten-free traditional staple for health-conscious global markets.',
    description: 'Stone-ground pearl millet flour rich in dietary fiber, protein, iron, and essential minerals. Gluten-free super-grain flour for health food and traditional cuisine applications.',
    image: IMAGES.milletFlour,
    overviewParagraphs: [
      'Our millet flour is stone-ground from premium pearl millet (bajra) grown in select Indian regions. Traditional milling preserves the natural nutritional profile and authentic flavor.',
      'High in fiber, protein, and minerals with a low glycemic index, our millet flour serves health food manufacturers, gluten-free bakeries, and ethnic food distributors worldwide.',
    ],
    overviewHighlights: ['Stone-ground traditional milling', 'High fiber, protein, and mineral content', 'Gluten-free and low glycemic index', 'Authentic flavor for traditional cuisine'],
    specs: [
      { label: 'Form', value: 'Fine flour' },
      { label: 'Color', value: 'Greyish-white to light brown' },
      { label: 'Protein', value: '~11–12%' },
      { label: 'Packaging', value: '5 kg, 10 kg, 25 kg multi-layer bags' },
      { label: 'Shelf Life', value: '12 months' },
    ],
    applications: [
      { title: 'Gluten-Free Baking', description: 'Alternative flour for gluten-free breads, cookies, pancakes, and multi-grain bakery products.' },
      { title: 'Health Food Manufacturing', description: 'High-fiber ingredient for health bars, porridge mixes, breakfast cereals, and nutritional supplements.' },
      { title: 'Traditional Cuisine', description: 'Authentic ingredient for roti, bhakri, porridge, and traditional Indian flatbreads for ethnic food markets.' },
      { title: 'Baby & Weaning Foods', description: 'Nutrient-dense flour for infant cereals and weaning food formulations requiring natural nutrition.' },
    ],
    qualityItems: [
      'Stone-ground in hygienic milling facilities',
      'Tested for aflatoxins, pesticides, and heavy metals',
      'Moisture content controlled for flour stability',
      'Sieve analysis for consistent particle size',
      'Microbiological testing per food safety standards',
    ],
    packagingItems: [
      'Multi-layer paper bags with inner PE liner',
      'Moisture-proof for humidity-sensitive flour',
      '5 kg retail to 25 kg industrial pack sizes',
      'Vacuum-sealed options for extended freshness',
    ],
    exportItems: [
      'Container-load: 20–24 MT per 20-ft container',
      'LCL options available for market testing',
      'Full documentation: Packing List, Invoice, COO, Health Certificate',
      'Phytosanitary and fumigation certificates as required',
      'Flexible payment terms for regular buyers',
    ],
    metaTitle: 'Millet (Bajra) Flour',
    metaDescription: 'Stone-ground pearl millet flour — high fiber, protein, and minerals. Gluten-free super-grain flour for health food and traditional cuisine. Bulk export from India.',
    ogTitle: 'Millet Flour | RMRP Global Trade',
    ogDescription: 'Premium stone-ground millet flour for global health food and traditional cuisine markets — nutritious, gluten-free, export-ready.',
  },
  {
    slug: 'jowar-flour',
    name: 'Jowar (Sorghum) Flour',
    category: 'Agro Products',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Finely milled sorghum flour with mild flavor and excellent nutritional profile. Gluten-free alternative for baking and health foods.',
    description: 'Premium sorghum flour milled from high-quality jowar grain. Fine texture, mild flavor, and excellent nutritional profile for gluten-free and traditional food applications.',
    image: IMAGES.jowarFlour,
    overviewParagraphs: [
      'Our jowar flour is finely milled from premium sorghum grain, producing a smooth texture with mild, versatile flavor that adapts well to both traditional and contemporary recipes.',
      'Naturally gluten-free with good protein and fiber content, our sorghum flour serves the growing global demand for gluten-free alternatives in baking, snacks, and health foods.',
    ],
    overviewHighlights: ['Fine-milled smooth texture', 'Mild flavor adaptable to recipes', 'Naturally gluten-free', 'Good protein and fiber content'],
    specs: [
      { label: 'Form', value: 'Fine flour' },
      { label: 'Color', value: 'White to light cream' },
      { label: 'Protein', value: '~10–11%' },
      { label: 'Packaging', value: '5 kg, 10 kg, 25 kg bags' },
      { label: 'Shelf Life', value: '12 months' },
    ],
    applications: [
      { title: 'Gluten-Free Products', description: 'Base flour for gluten-free bread, pizza crust, cookies, and multi-purpose gluten-free baking mixes.' },
      { title: 'Traditional Flatbreads', description: 'Essential ingredient for jowar roti/ bhakri and traditional Indian cuisine for ethnic food markets.' },
      { title: 'Snack Foods', description: 'Flour base for traditional and contemporary snack products including chips, crackers, and extruded snacks.' },
      { title: 'Breakfast Cereals', description: 'Ingredient for porridge mixes, hot cereals, and breakfast food formulations requiring gluten-free grains.' },
    ],
    qualityItems: [
      'Milled in hygienic facilities with quality control',
      'Moisture content analysis for flour stability',
      'Sieve analysis for consistent fine texture',
      'Microbiological testing per food standards',
      'Certificate of Analysis available per batch',
    ],
    packagingItems: [
      'Multi-layer bags with inner PE liner',
      'Moisture-protected for sea freight',
      '5 kg to 25 kg pack size range',
      'Private labeling for retail brands',
    ],
    exportItems: [
      'Container-load: 20–24 MT per 20-ft container',
      'LCL for trial market entry',
      'Full export documentation provided',
      'Competitive freight rates',
      'Flexible payment structures negotiable',
    ],
    metaTitle: 'Jowar (Sorghum) Flour',
    metaDescription: 'Finely milled sorghum flour — gluten-free, mild flavor, excellent nutrition. Premium quality for baking, snacks, and health foods. Bulk export from India.',
    ogTitle: 'Jowar Flour | RMRP Global Trade',
    ogDescription: 'Premium sorghum flour for global gluten-free and health food markets — fine texture, versatile, export-ready.',
  },
  {
    slug: 'wheat-flour',
    name: 'Wheat Flour',
    category: 'Agro Products',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Premium wheat flour milled from high-protein Indian wheat for commercial bakeries, chapati manufacturing, and pasta production.',
    description: 'High-quality wheat flour milled from select Indian wheat varieties. Consistent gluten development for commercial baking, chapati production, and pasta manufacturing.',
    image: IMAGES.wheatFlour,
    overviewParagraphs: [
      'Our wheat flour is milled from high-protein Indian wheat varieties, offering consistent gluten development and reliable performance across baking, chapati, and pasta applications.',
      'Available in atta (whole wheat) and maida (refined) grades, our wheat flour serves commercial bakeries, chapati manufacturers, pasta producers, and food service operators worldwide.',
    ],
    overviewHighlights: ['High protein content for strong gluten', 'Consistent performance batch to batch', 'Atta and maida grades available', 'Bulk supply for commercial buyers'],
    specs: [
      { label: 'Grade', value: 'Atta (whole wheat) / Maida (refined)' },
      { label: 'Protein', value: '~11–13%' },
      { label: 'Moisture', value: '< 14%' },
      { label: 'Packaging', value: '5 kg, 10 kg, 25 kg, 50 kg bags' },
      { label: 'Shelf Life', value: '12 months' },
    ],
    applications: [
      { title: 'Commercial Bakeries', description: 'Bread, buns, pastries, and bakery products requiring consistent gluten strength and reliable performance.' },
      { title: 'Chapati & Flatbread Manufacturing', description: 'Atta grade for automated chapati production lines serving retail and food service channels.' },
      { title: 'Pasta & Noodle Production', description: 'Durum and refined wheat grades for pasta, noodles, and couscous manufacturing.' },
      { title: 'Food Service & HoReCa', description: 'Bulk flour supply for hotels, restaurants, catering, and institutional kitchens.' },
    ],
    qualityItems: [
      'Gluten strength and farinograph testing per batch',
      'Moisture, ash, and protein analysis',
      'Sieve analysis for consistent granulation',
      'Microbiological testing for food safety',
      'Certificate of Analysis with every shipment',
    ],
    packagingItems: [
      'PP woven bags with inner liner for moisture protection',
      'Paper bags for retail channel distribution',
      '5 kg to 50 kg pack size range',
      'Bulk container liner systems available',
    ],
    exportItems: [
      'Container-load: 24–26 MT per 20-ft container',
      'Bulk vessel options for large volumes',
      'Full documentation: Packing List, Invoice, COO, Health Certificate',
      'Fumigation certificate as required',
      'Flexible incoterms and payment terms',
    ],
    metaTitle: 'Wheat Flour',
    metaDescription: 'Premium wheat flour from India — atta and maida grades. High protein, consistent gluten. Bulk export for commercial bakeries, chapati, and pasta manufacturers.',
    ogTitle: 'Wheat Flour | RMRP Global Trade',
    ogDescription: 'Premium Indian wheat flour for global commercial baking and food manufacturing — consistent quality, bulk supply.',
  },
  {
    slug: 'maize-flour',
    name: 'Maize (Corn) Flour',
    category: 'Agro Products',
    categoryHref: '/products/food-agro',
    heroSubheading: 'Fine-ground maize flour with natural sweetness and golden color for tortillas, snacks, breakfast cereals, and gluten-free baking.',
    description: 'Premium maize flour milled from select Indian corn. Fine texture with natural golden color and sweet flavor for food processing and direct food use.',
    image: IMAGES.maizeFlour,
    overviewParagraphs: [
      'Our maize flour is finely milled from premium Indian corn, producing a smooth, bright yellow flour with natural sweetness and versatile culinary applications.',
      'Naturally gluten-free with good carbohydrate energy profile, our maize flour serves snack manufacturers, tortilla producers, breakfast cereal makers, and gluten-free bakeries.',
    ],
    overviewHighlights: ['Natural golden color', 'Fine consistent grind', 'Natural sweet flavor', 'Gluten-free and versatile'],
    specs: [
      { label: 'Form', value: 'Fine flour' },
      { label: 'Color', value: 'Bright yellow' },
      { label: 'Moisture', value: '< 12%' },
      { label: 'Packaging', value: '5 kg, 10 kg, 25 kg multi-layer bags' },
      { label: 'Shelf Life', value: '12 months' },
    ],
    applications: [
      { title: 'Tortilla & Snack Production', description: 'Base flour for corn tortillas, tortilla chips, extruded snacks, and corn-based snack foods.' },
      { title: 'Breakfast Cereals', description: 'Ingredient for corn flakes, porridge, hot cereals, and breakfast food formulations.' },
      { title: 'Gluten-Free Baking', description: 'Alternative flour for gluten-free breads, muffins, pancakes, and multi-purpose baking blends.' },
      { title: 'Thickening & Food Processing', description: 'Natural thickener for soups, sauces, gravies, and prepared food products requiring clean-label ingredients.' },
    ],
    qualityItems: [
      'Milled from select Indian corn varieties',
      'Moisture content controlled for flour stability',
      'Sieve analysis for consistent particle size',
      'Microbiological testing per food safety standards',
      'Aflatoxin testing as per regulatory requirements',
    ],
    packagingItems: [
      'Multi-layer bags with inner PE liner',
      'Moisture-protected for sea freight',
      '5 kg to 25 kg pack size options',
      'Private labeling and custom packaging available',
    ],
    exportItems: [
      'Container-load: 20–24 MT per 20-ft container',
      'LCL options for trial quantities',
      'Full export documentation provided',
      'Phytosanitary and fumigation certificates as required',
      'Flexible payment terms negotiable',
    ],
    metaTitle: 'Maize (Corn) Flour',
    metaDescription: 'Fine-ground maize flour with natural golden color and sweetness. Gluten-free, versatile for tortillas, snacks, cereals, and baking. Bulk export from India.',
    ogTitle: 'Maize Flour | RMRP Global Trade',
    ogDescription: 'Premium maize flour for global food manufacturing — naturally golden, gluten-free, export-ready.',
  },
];

export default products;

export function getProductBySlug(slug: string): ProductData | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(slug: string, count = 4): ProductData[] {
  const product = getProductBySlug(slug);
  if (!product) return [];
  return products
    .filter((p) => p.slug !== slug && p.category === product.category)
    .slice(0, count);
}

export function getAllSlugs(): string[] {
  return products.map((p) => p.slug);
}
